apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 26.4.2
    chart: kafka
    helm:
      values: |
        replicaCount: 3
        auth:
          enabled: false
        zookeeper:
          auth:
            enabled: false
        persistence:
          enabled: true
          size: 8Gi
          storageClass: gp2-2b
        listeners:
          client:
            protocol: PLAINTEXT
        advertisedListeners:
          client: PLAINTEXT://kafka.kafka.svc.cluster.local:9092
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
