apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/100-hours-a-week/19-Respec-Infra.git
    targetRevision: prod
    path: charts/kafka
    helm:
      releaseName: kafka
      valueFiles:
        - ../../apps/kafka/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
