# Kraft 비활성화
kafka:
  enableKraft: false

kraft:
  enabled: false   # 이건 없어도 되지만, chart 내부에서 두 키가 분리되어 있다면 유지

# Zookeeper 설정
zookeeper:
  enabled: true
  replicaCount: 3
  persistence:
    enabled: true
  auth:
    enabled: false  # Zookeeper 자체 인증 비활성화

# Kafka 인증 설정 (중앙 통제)
auth:
  enabled: false
  zookeeper:
    enabled: false  # Kafka → Zookeeper 인증도 비활성화

sasl:
  enabled: false
  enabledMechanisms: ""
  interBrokerMechanism: ""
  controllerMechanism: ""
  client:
    users: []

# Kafka Broker 설정
broker:
  replicaCount: 1

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                  - ap-northeast-2c

  configurationConfigMap: ""  # 외부 설정 없이 overrides 사용

  configOverrides:
    server:
      - listeners=PLAINTEXT://:9092
      - advertised.listeners=PLAINTEXT://$(POD_NAME).kafka-broker-headless.kafka.svc.cluster.local:9092
      - listener.security.protocol.map=PLAINTEXT:PLAINTEXT
      - security.inter.broker.protocol=PLAINTEXT
      - inter.broker.listener.name=PLAINTEXT
      - zookeeper.connect=kafka-zookeeper-headless.kafka.svc.cluster.local:2181

  extraEnvVars:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name

  existingSecret: ""
  interBrokerUser: ""
  interBrokerPassword: ""
  clientUser: ""
  clientPassword: ""

# 저장소 설정
persistence:
  enabled: true
  storageClass: kafka-gp2-wffc
