controller:
  enabled: false              # KRaft 모드 비활성화

broker:
  replicaCount: 3             # 브로커 3개 구성
  config:
    listeners: PLAINTEXT://:9092
    advertised.listeners: PLAINTEXT://kafka.kafka.svc.cluster.local:9092
    log.retention.hours: 168
    zookeeper.connect: kafka-zookeeper-headless:2181

zookeeper:
  enabled: true
  replicaCount: 3

auth:
  clientProtocol: plaintext
  interBrokerProtocol: plaintext
