apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatconsumer-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/100-hours-a-week/19-Respec-Infra.git
    targetRevision: prod
    path: helm/chatconsumer
    helm:
      valueFiles:
        - dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: chatconsumer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
