apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chatconsumer.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "chatconsumer.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "chatconsumer.name" . }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      volumes:
        - name: config-volume
          secret:
            secretName: chatconsumer-properties
      containers:  # ✅ 이 위치에 있어야 함
        - name: chatconsumer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config/chatconsumer-app-secret
              subPath: application.properties
              readOnly: true
