apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatconsumer.fullname" . }}
spec:
  selector:
    app: {{ include "chatconsumer.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
  type: ClusterIP
