replicaCount: 2

image:
  repository: 115313776476.dkr.ecr.ap-northeast-2.amazonaws.com/specranking-backend-dev
  tag: dev-0f23370
  pullPolicy: Always

imagePullSecrets:
  - name: ecr-secret


service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
#인증서 arn
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:115313776476:certificate/25a254b7-38c9-4654-9da7-112f0de38ffc
    alb.ingress.kubernetes.io/group.name: specranking-apps
  hosts:
    - host: dev.specranking.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - dev.specranking.com


resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
env:
  - name: HOST_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP

# env:
#   - name: SPRING_PROFILES_ACTIVE
#     value: dev
#   - name: OTEL_EXPORTER_OTLP_ENDPOINT
#     value: http://otel-collector.monitoring.svc:4317

# podAnnotations:
#   prometheus.io/scrape: "true"
#   prometheus.io/path: "/actuator/prometheus"
#   prometheus.io/port: "8080"
