replicaCount: 2

image:
  repository: 115313776476.dkr.ecr.ap-northeast-2.amazonaws.com/specranking-backend-dev
  tag: dev-0af45bc
  pullPolicy: Always

imagePullSecrets:
  - name: ecr-secret


service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30080
  sessionAffinity: ClientIP
ingress:
  enabled: true
  ingressClassName: alb
  annotations:
    kubernetes.io/ingress.class: alb
    
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:115313776476:certificate/eae89fe4-2ba9-424c-a0ce-ce90e08d981e
    alb.ingress.kubernetes.io/group.name: specranking-apps
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/connection-idle-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/enable-websocket: "true"

  hosts:
    - host: dev.specranking.net
      paths:
        - path: /ws/chat
          pathType: Prefix
          backend:
            service:
              name: backend-main
              port:
                number: 80
                
        - path: /
          pathType: Prefix
          backend:
            service:
              name: backend-main
              port:
                number: 80

  tls:
    - hosts:
        - dev.specranking.net


resources:
  requests:
    cpu: 1
    memory: 1.5Gi
  limits:
    cpu: 1
    memory: 2Gi

# env:
#   - name: HOST_IP
#     valueFrom:
#       fieldRef:
#         fieldPath: status.hostIP
env:
  - name: HOST_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP

# env:
#   - name: SPRING_PROFILES_ACTIVE
#     value: dev
#   - name: OTEL_EXPORTER_OTLP_ENDPOINT
#     value: http://otel-collector.monitoring.svc:4317

# podAnnotations:
#   prometheus.io/scrape: "true"
#   prometheus.io/path: "/actuator/prometheus"
#   prometheus.io/port: "8080"
