apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: default
data:
  SPRING_APPLICATION_NAME: spec-ranking
  SPRING_PROFILES_ACTIVE: auth,ai,imageS3,resumeS3,no-local,no-spec-initialize,no-user-initialize,no-chat-initialize
  MOCK_LOGIN_USER: "false"
  SPRING_JPA_HIBERNATE_DDL_AUTO: none
  SPRING_JPA_SHOW_SQL: "false"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "false"
  BACKEND_BASE_URL: https://api.specranking.net
  FRONTEND_BASE_URL: https://specranking.net
  FRONTEND_REDIRECT_URL: https://specranking.net/oauth-redirect
  CLOUD_AWS_REGION_STATIC: ap-northeast-2
  CLOUD_AWS_STACK_AUTO: "false"
  SPRING_DATA_REDIS_HOST: specranking-dev-redis.q13o6s.ng.0001.apn2.cache.amazonaws.com
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: ##:9092###서버 아이피 넣기 dns 붙일지 고민
  SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
  SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
  SPRING_KAFKA_CHAT_TOPIC_PARTITIONS: "3"
  SPRING_KAFKA_CHAT_TOPIC_REPLICAS: "1"
  SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 10MB
  SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 20MB
  SERVER_PRIVATE_ADDRESS: 10.0.11.28:80
  LOGGING_FILE_NAME: /var/log/myapp/app.log
  LOGGING_LEVEL_ROOT: INFO
