apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-token-refresh
  namespace: backend-main
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ecr-refresh-sa
          containers:
            - name: ecr-login
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - |
                  apt update && apt install -y awscli && \
                  aws ecr get-login-password --region ap-northeast-2 | \
                  kubectl create secret docker-registry backend-secret \
                    --docker-server=115313776476.dkr.ecr.ap-northeast-2.amazonaws.com \
                    --docker-username=AWS \
                    --docker-password="$(cat -)" \
                    --namespace=backend-main \
                    --dry-run=client -o yaml | kubectl apply -f -

          restartPolicy: OnFailure
