apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-main-dev
  labels:
    app: backend-main-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-main-dev
  template:
    metadata:
      labels:
        app: backend-main-dev
    spec:
      containers:
        - name: backend-main
          image: 115313776476.dkr.ecr.ap-northeast-2.amazonaws.com/specranking-backend-dev:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: backend-main-dev-config
            - secretRef:
                name: backend-main-dev-secret
          livenessProbe:
            httpGet:
            #헬스체크 경로 변경 필요
              path: /healthz
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
