#임시로 작성한 것이므로 완전히 바꿔야함
apiVersion: v1
kind: Secret
metadata:
  name: backend-main-dev-secret
type: Opaque
stringData:
  DATABASE_URL: postgres://user:password@db.dev.example.com:3306/devdb
  JWT_SECRET: dev-secret-key
