replicaCount: 2

image:
  repository: 115313776476.dkr.ecr.ap-northeast-2.amazonaws.com/chatconsumer-backend-dev
  tag: dev-f34df19
  pullPolicy: Always

imagePullSecrets:
  - name: ecr-secret

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
containerPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

env:
  SPRING_PROFILES_ACTIVE: dev
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka.kafka.svc.cluster.local:9092
  SPRING_REDIS_HOST: redis.redis.svc.cluster.local
