data:
  server.properties: |-
{{- if and .Values.broker.configOverrides (hasKey .Values.broker.configOverrides "server") }}
{{- range .Values.broker.configOverrides.server }}
    {{ . }}
{{- end }}
{{- else }}
    # Listeners configuration
    listeners={{ include "kafka.listeners" (dict "isController" false "context" $) }}
    listener.security.protocol.map={{ include "kafka.securityProtocolMap" . }}
    advertised.listeners={{ include "kafka.advertisedListeners" . }}
    {{- if .Values.kraft.enabled }}
    {{- if not .Values.broker.zookeeperMigrationMode }}
    process.roles=broker
    {{- end }}
{{ include "kafka.kraftConfig" . | nindent 4 }}
    {{- end }}
    {{- if or .Values.zookeeper.enabled .Values.externalZookeeper.servers }}
{{ include "kafka.zookeeperConfig" . | nindent 4 }}
    {{- if .Values.broker.zookeeperMigrationMode }}
    zookeeper.metadata.migration.enable=true
    inter.broker.protocol.version={{ default (regexFind "^[0-9].[0-9]+" .Chart.AppVersion) .Values.interBrokerProtocolVersion }}
    {{- end }}
    {{- end }}
{{ include "kafka.commonConfig" . | nindent 4 }}
{{ include "common.tplvalues.render" (dict "value" .Values.extraConfig "context" $) | nindent 4 }}
{{ include "common.tplvalues.render" (dict "value" .Values.broker.extraConfig "context" $) | nindent 4 }}
{{- end }}




